services:
  dev:
    build:
      context: .
      dockerfile: .Dockerfile
    tty: true
    stdin_open: true
    working_dir: /workspace
    environment:
      - UNI_TARGET_SOURCE=${UNI_TARGET_SOURCE:-}
    volumes:
      - .:/workspace
      - ./.uni:/workspace/.uni
      - target_workspace:/target
      - ${UNI_TARGET_SOURCE:-/tmp/empty}:/host_target:ro
      - ${UNI_HOST_ROOT:-/tmp/empty}:/host_root:ro

volumes:
  target_workspace:
